# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: nectar
description: "Keep sipping that nectar, king. The bees are proud of you."

base-image: quay.io/fedora/fedora-silverblue
image-version: 43

modules:
  - type: dnf
    repos:
      cleanup: false
      copr:
        - dennemann/MangoWC
    install:
      packages:
        - mangowc
        - scenefx
        - wlroots
        - adw-gtk3-theme
        - helix
        - kitty
        - waybar
        - distrobox

    remove:
      packages:
        - malcontent-control
        - gnome-software
        - gnome-disk-utility
        - gnome-system-monitor
        - gnome-tour
        - gnome-user-docs
        - gnome-extensions-app
        - gnome-color-manager
        - rygel
        - ptyxis

  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    configurations:
      - notify: false
        repo:
          title: Flathub
        install:
          - com.saivert.pwvucontrol
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark

  - type: script
    scripts:
      - remove-gnome-session.sh

  - type: os-release
    properties:
      ID: nectar
      NAME: nectar
      PRETTY_NAME: "nectar"
      HOME_URL: "https://github.com/christian-bendiksen/nectaros"
      BUG_REPORT_URL: "https://github.com/christian-bendiksen/nectaros/issues"
      DEFAULT_HOSTNAME: nectar
  - type: initramfs
  - type: signing
