#!/usr/bin/bash
set -euo pipefail

# Flatpak
echo "Installing Flatpak packages..."

# Add Flathub (system scope) if it doesn't already exist
if ! flatpak remote-list --user | grep -q flathub; then
    flatpak remote-add --if-not-exists --user flathub \
        https://dl.flathub.org/repo/flathub.flatpakrepo
fi

notify-send "Setup" "System flatpaks are being installed"
flatpak install -y --user \
    io.github.kolunmi.Bazaar \
    app.devsuite.Ptyxis \
    org.mozilla.firefox \
    org.gtk.Gtk3theme.adw-gtk3 \
    org.gtk.Gtk3theme.adw-gtk3-dark \
    com.saivert.pwvucontrol

echo "All packages installed successfully!"

echo "Setting flatpak theme permissions"
flatpak override --user --filesystem=xdg-config/gtk-3.0:ro
flatpak override --user --filesystem=xdg-config/gtkrc-2.0:ro
flatpak override --user --filesystem=xdg-config/gtk-4.0:ro
flatpak override --user --filesystem=xdg-config/gtkrc:ro

flatpak mask --user org.gtk.Gtk3theme.adw-gtk3
flatpak mask --user org.gtk.Gtk3theme.adw-gtk3-dark

# GTK
if command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface gtk-theme        'adw-gtk3-dark'
    gsettings set org.gnome.desktop.interface color-scheme     'prefer-dark'
fi

# Done
mkdir -p "${HOME}/.config"
touch "${HOME}/.config/.first-login-done"
